name: OpenWrt-CI

on:
  push:
    branches: 
      - master
    paths:
      - '.github/workflows/OpenWrt-CI.yml'
  schedule:
    - cron: '0 */8 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler zip unzip
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          df -h
          pwd
          dir
 
      - name: clone git
        run: |
          git clone https://github.com/openwrt/openwrt.git
          pwd
          dir
      - name: Update feeds
        run: |
          pwd
          dir
          ./scripts/feeds update -a
          ./scripts/feeds install -a
  
      - name: Generate configuration file
        run: |
          pwd
          dir
          make defconfig
          #cat ../.config > ./.config          
  
      - name: Make download
        run: |
          pwd
          dir
          make download -j8
          find ./dl/ -size -1024c -exec rm -f {} \;
          df -h
 
      - name: Compile firmware
        run: |
          pwd
          dir
          make V=99          
      - name: Prepare artifact
        run: |
          pwd
          dir
          ls ./bin
          ls ./target
          find ./bin/targets/ -type d -name "packages" | xargs rm -rf {}
                
      - name: Prepare artifact
        run: |
          pwd
          dir ./
          ls bin/targets/
          ls target/
          
          #zip package.zip ./bin/targets/
          #cp -r package.zip ./actifact/
          #cp -r ./bin/targets/ ./artifact/
          #cp ./.config ./artifact/
          
      - name: Zip Files
        run: |
          find bin/targets/ -name "openwrt_*img*" | xargs -i zip -r {}.zip {}
          
      - name: Assemble Artifact
        run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          find bin/targets/ -name "openwrt_*img.zip*" | xargs -i mv -f {} ./artifact/
                    
          UPLOAD_WERANSFER: true
          
      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: openwrt
          path: ./artifact/
          
          
