name: openwrt19

on:
  push:
    branches: 
      - master
    paths:
      - '.github/workflows/openwrt19.yml'
  schedule:
    - cron: '0 16 */7 * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |          
          sudo rm -rf /etc/apt/sources.list.d          
          sudo apt-get update
          sudo apt-get -y install subversion build-essential libncurses5-dev zlib1g-dev gawk git ccache gettext libssl-dev xsltproc zip
          sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3.5 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          df -h
 
      - name: clone git
        run: |
          cd /home/runner/
          git clone -b dev-19.07 https://github.com/Lienol/openwrt op19
          
      - name: Update install feeds
        run: |
          cd /home/runner/op19/
          ./scripts/feeds clean
          ./scripts/feeds update -a
          ./scripts/feeds install -a
  
      - name: Generate configuration file
        run: |
          cd /home/runner/op19/
          make defconfig
          wget https://raw.githubusercontent.com/uosX/openwrt/master/op19.config
          cat op19.config > .config
          cat .config

          #sed -i 's/192.168.1.1/172.16.10.254/g' package/base-files/files/bin/config_generate
          #sed -i 's/192.168.\$((addr_offset++)).1/172.16.\$((addr_offset++)).254/g' package/base-files/files/bin/config_generate
          #sed -i 's/255.255.255.0/255.255.255.128/g' package/base-files/files/bin/config_generate
          #sed -i 108a\\"                set network.\$1.gateway='172.16.10.254" package/base-files/files/bin/config_generate
          #sed -i 109a\\"                set network.\$1.dns='127.0.0.1 223.5.5.5 8.8.8.8" package/base-files/files/bin/config_generate
          
          
          cp /usr/bin/upx /home/runner/op19/staging_dir/host/bin/
          cp /usr/bin/upx-ucl /home/runner/op19/staging_dir/host/bin/
          
      - name: Make download
        run: |
          cd /home/runner/op19/
          make -j8 download V=s
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;
          
      - name: Compile firmware
        run: |
          cd /home/runner/op19/
          echo -e "$(nproc) thread build."
          make -j$(nproc) V=s
          
      - name: Prepare artifact
        run: |
          cd /home/runner/op19/
          cp .config bin
          
      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: openwrt
          path: /home/runner/op19/bin
          
          
