
name: openwrt fq
on:
  push:
    branches: 
      - master
    paths:
      - '.github/workflows/openwrt_fq.yml'
    
  schedule:
    - cron: '0 18 */5 * *'

env:
  SSH_ACTIONS: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    #if: github.repository == 'uosX/openwrt'
    
    steps:  

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |          
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo apt-get update
          sudo apt-get -y install subversion build-essential libncurses5-dev zlib1g-dev gawk git ccache gettext libssl-dev xsltproc zip
          sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3.5 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget
          sudo apt-get -y autoremove --purge
          sudo apt-get clean
                     
      - name: clone git
        run: |
          cd /home/runner/openwrt/
          git clone https://git.openwrt.org/openwrt/openwrt.git
          
          cd openwrt/
          
          git fetch --tags
          git tag -l
          git checkout v19.07.3
          
          cd /home/runner/openwrt/
          git clone https://github.com/coolsnowwolf/lede
          
          cp -r lede/package/lean/ openwrt/package/
          
      #- name: Setup Debug Session
      #  uses: P3TERX/debugger-action@master                   
          
      - name: change Update install feeds
        run: |
          cd /home/runner/openwrt/openwrt
          sed -i 's/https:\/\/git.openwrt.org\/feed\/packages.git^2e6bd4cb86682b224803325127d3f777d40b3231/https:\/\/github.com\/coolsnowwolf\/packages/' feeds.conf.default
          sed -i 's/https:\/\/git.openwrt.org\/project\/luci.git^fb2f36306756d0d0782dcab8413a8bb7ec379e54/https:\/\/github.com\/coolsnowwolf\/luci/' feeds.conf.default
          echo "src-git helloworld https://github.com/fw876/helloworld" >> feeds.conf.default
              
          ./scripts/feeds update -a     
          ./scripts/feeds install -a
  
      - name: Generate configuration file
        run: |
          cd /home/runner/openwrt/openwrt
          rm -rf .config
          wget https://raw.githubusercontent.com/uosX/openwrt/master/openwrt_fq.config    
          cat openwrt_fq.config > .config
          cat .config
          #make defconfig
  
      - name: Make download
        run: |          
          cd /home/runner/openwrt/openwrt
          make -j8 download V=99
        
      - name: Compile firmware
        run: |
          cd /home/runner/openwrt/openwrt
          make V=99
        
      - name: Prepare artifact
        run: |
          cd /home/runner/openwrt/openwrt
          
          rm -rf ./artifact/
          mkdir ./artifact/          
          pwd
                    
          cp .config ./artifact/
          
          ls /bin/targets/
          #ls bin/targets/x86/64
          
      - name: Setup Debug Session
        uses: P3TERX/debugger-action@master          
          
      #- name: Zip Files
      #  run: |
      #    find bin/targets/ -name "openwrt_*img*" | xargs -i zip -r {}.zip {}
          
      #- name: Assemble Artifact
      #  run: |
      #    rm -rf ./artifact/
      #    mkdir -p ./artifact/
      #    find bin/targets/ -name "openwrt_*img.zip*" | xargs -i mv -f {} ./artifact/
          
      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: openwrt
          path: ./artifact/
