name: OpenWrt-Default

on:
  push:
    branches: 
      - master
    paths:
      - '.github/workflows/OpenWrt-Default.yml'
  schedule:
    - cron: '0 */6 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          cat ../def.cfg
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo apt-get update          
          sudo apt-get -y install antlr3 asciidoc autoconf automake autopoint binutils build-essential bzip2 device-tree-compiler flex g++-multilib gawk gcc-multilib gettext git git-core gperf lib32gcc1 libc6-dev-i386 libelf-dev libglib2.0-dev libncurses5-dev libssl-dev libtool libz-dev msmtp p7zip p7zip-full patch python2.7 python3.5 qemu-utils subversion texinfo uglifyjs unzip upx wget xmlto zlib1g-dev
          sudo apt-get -y autoremove --purge
          sudo apt-get clean
 
      - name: clone git
        run: |          
          git clone https://github.com/openwrt/openwrt.git
          
          cd ../
          git clone https://github.com/coolsnowwolf/lede                    
          mv lede/package/lean/ openwrt/package/                    
          cat ../../def.cfg
      - name: Update feeds
        run: |
          pwd
          cd openwrt
          echo "src-git packages https://github.com/coolsnowwolf/packages" > feeds.conf.default
          echo "src-git luci https://github.com/coolsnowwolf/luci" >> feeds.conf.default
          echo "src-git routing https://git.openwrt.org/feed/routing.git" >> feeds.conf.default
          echo "src-git telephony https://git.openwrt.org/feed/telephony.git" >> feeds.conf.default
          echo "#src-git video https://github.com/openwrt/video.git" >> feeds.conf.default
          echo "#src-git targets https://github.com/openwrt/targets.git" >> feeds.conf.default
          echo "#src-git management https://github.com/openwrt-management/packages.git" >> feeds.conf.default
          echo "#src-git oldpackages http://git.openwrt.org/packages.git" >> feeds.conf.default
          echo "#src-link custom /usr/src/openwrt/custom-feed" >> feeds.conf.default
          echo "src-git helloworld https://github.com/fw876/helloworld" >> feeds.conf.default
          
          #cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          pwd
  
      - name: Generate configuration file
        run: |
          pwd
          dir
          cat ../../.config          
          make defconfig          
          cat ../.config > ./.config          
          cat ./.config
          pwd
  
      - name: Make download
        run: |          
          make -j8 download V=99
          #find ./dl/ -size -1024c -exec rm -f {} \;
          df -h
          pwd
 
      - name: Compile firmware
        run: |
          #cd openwrt
          make V=99
          pwd
          
      - name: Prepare artifact
        run: |
          cp ./.config ./artifact/
          cd ./bin/targets/
          ls ./bin/targets/
          ls ./targets/
          #zip -r pake.zip ./          
          #cp pake.zip ./artifact/
          pwd
          
      - name: Zip Files
        run: |
          find bin/targets/ -name "openwrt_*img*" | xargs -i zip -r {}.zip {}
          
      - name: Assemble Artifact
        run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          find bin/targets/ -name "openwrt_*img.zip*" | xargs -i mv -f {} ./artifact/
          
      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: openwrt
          path: ./artifact/
